#include "gs/surfacing/surfacing.hpp"

#include "gs/util/jsnumber.hpp"
#include "gs/util/units.hpp"

#include <algorithm>
#include <cmath>
#include <numbers>

namespace gs::surfacing {
namespace {

// Template literals print numbers with Number.prototype.toString().
std::string num(double value) {
    return js::numberToString(value);
}

// toFixedValue(): Number(value.toFixed(3)).
double fixed3(double value) {
    return js::stringToNumber(js::toFixed(value, 3));
}

// JS truthiness of a number.
bool truthy(double value) {
    return value != 0 && !std::isnan(value);
}

// Guards against inputs that never terminate upstream (a zero stepover or
// cut depth recurses until the stack overflows).
constexpr int kMaxPasses = 100000;

using Lines = std::vector<std::string>;

void append(Lines& to, const Lines& more) {
    to.insert(to.end(), more.begin(), more.end());
}

struct Direction {
    char axis;
    double factor;
};

struct Pos {
    double x;
    double y;
};

struct Layer {
    double depth;
    double stepoverAmount;
    double xFactor;
    double yFactor;
};

class Generator {
public:
    Generator(const Options& options, bool metric) : s_(options), metric_(metric) {}

    Lines generate() const {
        const double z = safeZ();
        const Lines dwell = s_.shouldDwell ? Lines{"G04 P4"} : Lines{};
        Lines code{"(Header)", "(Generated by gSender from Sienci Labs)", metric_ ? "G21 ;mm" : "G20 ;inches", "G90"};
        if (s_.toolNumber != 0) {
            code.push_back("M6 T" + num(s_.toolNumber));
        }
        code.push_back(s_.spindle + " S" + num(s_.spindleRPM));
        append(code, dwell);
        code.emplace_back("G0 X0 Y0");
        code.push_back("G0 Z" + num(z));
        if (s_.mist) {
            code.emplace_back("M7");
        }
        if (s_.flood) {
            code.emplace_back("M8");
        }
        code.push_back("G1 F" + num(s_.feedrate));
        code.emplace_back("(Header End)");
        code.emplace_back("\n");

        // One layer per cut depth, the last one at the maximum depth.
        double depth = s_.skimDepth;
        for (int count = 1;; ++count) {
            append(code, layer(depth < s_.maxDepth ? depth : s_.maxDepth, count));
            if (depth >= s_.maxDepth || !(s_.skimDepth > 0) || count >= kMaxPasses) {
                break;
            }
            depth = depth + s_.skimDepth;
        }

        code.emplace_back("(Footer)");
        if (s_.mist || s_.flood) {
            code.emplace_back("M9 ;Turn off Coolant");
        }
        code.emplace_back("M5 ;Turn off spindle");
        append(code, dwell);
        code.emplace_back("(End of Footer)");
        return code;
    }

private:
    double safeZ() const { return metric_ ? 3 : 0.12; }

    // generateGcode()
    Lines layer(double depth, int count) const {
        const double stepoverPercentage = s_.stepover > 80 ? 80.0 / 100 : s_.stepover / 100;
        Layer l{depth, fixed3(s_.bitDiameter * stepoverPercentage), 1, -1};
        switch (s_.startPosition) {
            case StartPosition::BackLeft: l.xFactor = 1; l.yFactor = -1; break;
            case StartPosition::BackRight: l.xFactor = -1; l.yFactor = -1; break;
            case StartPosition::FrontLeft: l.xFactor = 1; l.yFactor = 1; break;
            case StartPosition::FrontRight: l.xFactor = -1; l.yFactor = 1; break;
            case StartPosition::Center: break;
        }
        const Lines passes = s_.type == Pattern::Spiral ? spiral(l) : zigZag(l);

        Lines code{"(*** Layer " + num(count) + " ***)"};
        if (count != 1) {
            const double z = fixed3(safeZ() - (depth - s_.skimDepth));
            append(code, {"(Move to Starting Height)", "G0 Z" + num(z), "(End of Move to Starting Height)", ""});
        }
        append(code, passes);
        code.push_back("(*** End of Layer " + num(count) + " ***)");
        code.emplace_back("\n");
        return code;
    }

    // rampIntoMaterial(): a zig-zag down to the cut depth at 2 degrees at
    // most, with an even number of legs so it ends where it started.
    Lines ramp(Direction direction) const {
        const double totalZDrop = safeZ() + std::fabs(s_.skimDepth);
        const double minDimension = std::min(std::fabs(s_.width), std::fabs(s_.length));
        const double maxZigzagLength = metric_ ? 150 : fixed3(150 / 25.4);
        const double zigzagLength = std::max(s_.bitDiameter, std::min(minDimension - s_.bitDiameter, maxZigzagLength));
        const double zPerLeg = zigzagLength * std::tan((2 * std::numbers::pi) / 180);
        const double numLegsRaw = std::ceil(totalZDrop / zPerLeg);
        double numLegs = std::fmod(numLegsRaw, 2) == 0 ? numLegsRaw : numLegsRaw + 1;
        if (!std::isfinite(numLegs) || numLegs > kMaxPasses) {
            numLegs = 0;  // upstream loops forever
        }
        const double actualZPerLeg = fixed3(totalZDrop / numLegs);
        Lines code{"(Ramping into Material)", "G91"};
        for (int i = 0; i < static_cast<int>(numLegs); ++i) {
            const double legFactor = i % 2 == 0 ? direction.factor : direction.factor * -1;
            code.push_back(std::string("G1 ") + direction.axis + num(fixed3(zigzagLength * legFactor)) + " Z" +
                           num(-actualZPerLeg));
        }
        append(code, {"G90", "(End of Ramping into Material)", ""});
        return code;
    }

    // drawInitialPerimeter(); the zig-zag passes no start position (and so
    // never the centred form) and no cut direction.
    Lines perimeter(double x, double y, Direction direction, std::optional<StartPosition> start,
                    bool flipped) const {
        Lines main{"G91",
                   "G1 Y" + num(std::fabs(y) * -1),
                   "G1 X" + num(std::fabs(x)),
                   "G1 Y" + num(std::fabs(y)),
                   "G1 X" + num(std::fabs(x) * -1),
                   "G90"};
        if (start != StartPosition::Center) {
            main = flipped ? Lines{"G1 X" + num(x), "G1 Y" + num(y), "G1 X0", "G1 Y0"}
                           : Lines{"G1 Y" + num(y), "G1 X" + num(x), "G1 Y0", "G1 X0"};
        }
        Lines code{"(Covering Surfacing Perimeter)"};
        append(code, ramp(direction));
        append(code, main);
        append(code, {"(End of Covering Surfacing Perimeter)", ""});
        return code;
    }

    // enterSpiralStartArea(x, y, false, 'G1', lastAxis)
    static Lines enterSpiralStart(double x, double y, char lastAxis) {
        Lines code{"(Entering Start Position)", "G91"};
        const std::string X = "X" + num(x);
        const std::string Y = "Y" + num(y);
        if (lastAxis == 'X') {
            if (truthy(y)) {
                code.push_back("G1 " + Y);
            }
            if (truthy(x)) {
                code.push_back("G1 " + X);
            }
        } else {
            if (truthy(x)) {
                code.push_back("G1 " + X);
            }
            if (truthy(y)) {
                code.push_back("G1 " + Y);
            }
        }
        append(code, {"G90", "(End of Entering Start Position)", ""});
        return code;
    }

    Lines returnToZero() const {
        return {"(Returning to Zero)", "G0 Z" + num(safeZ()), "G0 X0 Y0", "(End of Returning to Zero)", ""};
    }

    Lines spiral(const Layer& l) const {
        const double so = l.stepoverAmount;
        const bool center = s_.startPosition == StartPosition::Center;
        const bool flipped = s_.cutDirectionFlipped;
        const double width = s_.width;
        const double length = s_.length;
        const double x = fixed3(width * l.xFactor);
        const double y = fixed3(length * l.yFactor);
        const double halfOfLength = fixed3(length / 2);
        const double halfOfWidth = fixed3(width / 2);

        Pos start{flipped ? 0 : fixed3(so), flipped ? fixed3(so * 2) : fixed3(so)};
        Pos end{fixed3(width - so), fixed3(length - so)};
        Direction direction{'Y', l.yFactor};
        if (width >= length) {
            direction = {'X', l.xFactor};
        }

        // The spiral loops, inwards; the last X and Y it moves to (upstream
        // runs the lines through a toolpath to find them).
        Lines spirals;
        Pos last{0, 0};
        const auto moveX = [&](double value) {
            spirals.push_back("G1 X" + num(value));
            last.x = value;
        };
        const auto moveY = [&](double value) {
            spirals.push_back("G1 Y" + num(value));
            last.y = value;
        };
        for (int pass = 0;; ++pass) {
            const double xValueStart =
                center ? fixed3((halfOfWidth - end.x) * l.xFactor) : fixed3(end.x * l.xFactor);
            const double yValueStart =
                center ? fixed3((halfOfLength - end.y) * l.yFactor) : fixed3(end.y * l.yFactor);
            const double xValueEnd = center ? fixed3((halfOfWidth - (start.x + so)) * l.xFactor)
                                            : fixed3((start.x + so) * l.xFactor);
            const double yValueEnd =
                center ? fixed3((halfOfLength - start.y) * l.yFactor) : fixed3(start.y * l.yFactor);
            if (flipped) {
                if (end.x >= start.x) {
                    moveX(xValueStart);
                    if (length >= width) {
                        moveY(yValueStart);
                        moveX(xValueEnd);
                    }
                    if (end.y >= start.y) {
                        if (width > length) {
                            moveY(yValueStart);
                            moveX(xValueEnd);
                        }
                        moveY(yValueEnd);
                    }
                }
            } else {
                if (end.y >= start.y) {
                    moveY(yValueStart);
                    if (width >= length) {
                        moveX(xValueStart);
                        moveY(yValueEnd);
                    }
                } else {
                    moveY(yValueStart);
                }
                if (end.x >= start.x) {
                    if (length > width) {
                        moveX(xValueStart);
                        moveY(yValueEnd);
                    }
                    moveX(end.y < start.y ? xValueStart : xValueEnd);
                }
            }
            spirals.emplace_back("");
            if (end.x < start.x || end.y < start.y || !(so > 0) || pass >= kMaxPasses) {
                break;
            }
            start = {fixed3(start.x + so), fixed3(start.y + so)};
            end = {fixed3(end.x - so), fixed3(end.y - so)};
        }

        Lines code;
        if (!center) {
            append(code, perimeter(x, y, direction, s_.startPosition, flipped));
            append(code, enterSpiralStart(so * l.xFactor, so * l.yFactor, direction.axis));
            append(code, spirals);
            append(code, returnToZero());
            return code;
        }

        // From the centre: trace the perimeter around it, then run the
        // spiral backwards, outwards from its innermost loop.
        const double z = fixed3(safeZ() - (l.depth - s_.skimDepth));
        append(code, {"(Entering Perimeter Start Position)",
                      "G0 X" + num(halfOfWidth * -1) + " Y" + num(halfOfLength),
                      "(End of Entering Perimeter Start Position)", ""});
        append(code, perimeter(width, length, direction, s_.startPosition, false));
        append(code, {"(Entering Start Position)", "G0 X" + num(last.x) + " Y" + num(last.y),
                      "G0 Z" + num(z) + " ; Start Pos - (Curr Depth - Cut Depth)", "G91",
                      "G0 Z" + num(std::fabs(l.depth) * -1 - safeZ()), "G90", "(End of Entering Start Position)", ""});
        code.insert(code.end(), spirals.rbegin(), spirals.rend());

        const double remainderXFactor = flipped ? 1 : -1;
        const double remainderYFactor = flipped ? -1 : 1;
        if (flipped) {
            append(code, {"", "(Cover Remaining Area)",
                          "G1 Y" + num(fixed3(std::fabs(halfOfLength - so) * remainderYFactor)),
                          "G1 X" + num(fixed3(std::fabs(halfOfWidth - so) * remainderXFactor * -1)),
                          "G1 X" + num(fixed3(std::fabs(halfOfWidth - so) * remainderXFactor)),
                          // (upstream uses the X factor here)
                          "G1 Y" + num(fixed3(std::fabs(halfOfLength) * remainderXFactor * -1)),
                          "(End of Cover Remaining Area)", ""});
        } else {
            append(code, {"", "(Cover Remaining Area)",
                          "G1 X" + num(fixed3(std::fabs(halfOfWidth - so) * remainderXFactor * -1)),
                          "G1 Y" + num(fixed3(std::fabs(halfOfLength) * -remainderYFactor)),
                          "(End of Cover Remaining Area)", ""});
        }
        append(code, returnToZero());
        return code;
    }

    Lines zigZag(const Layer& l) const {
        const double so = l.stepoverAmount;
        const bool center = s_.startPosition == StartPosition::Center;
        const bool flipped = s_.cutDirectionFlipped;
        const double width = s_.width;
        const double length = s_.length;
        const double x = fixed3(width * l.xFactor);
        const double y = fixed3(length * l.yFactor);
        const double halfOfLength = fixed3(length / 2);
        const double halfOfWidth = fixed3(width / 2);

        Pos start{flipped ? fixed3(so) : width, flipped ? length : fixed3(so)};
        Pos end{flipped ? fixed3(so * 2) : 0, flipped ? 0 : fixed3(so * 2)};
        Direction direction{'Y', l.yFactor};
        if (width > length) {
            direction = {'X', l.xFactor};
        }

        Lines passes;
        const auto push = [&](char axis, double value) { passes.push_back(std::string("G1 ") + axis + num(value)); };
        for (int pass = 0;; ++pass) {
            const Pos s = start;
            const Pos e = end;
            if (center) {
                const double hl = halfOfLength;
                const double hw = halfOfWidth;
                if (flipped) {
                    if (s.x - hw > hw && e.x - hw > hw && s.y - hl <= hl && e.y - hl <= hl) {
                        push('Y', fixed3(hl) * -1);
                    } else {
                        if (s.y - hl <= hl) {
                            push('Y', fixed3(hl) * -1);
                        }
                        if (s.x - hw <= hw) {
                            push('X', fixed3(hw * -1 + s.x));
                        }
                        if (e.y - hl <= hl) {
                            push('Y', fixed3(hl));
                        }
                        if (e.x - hw <= hw) {
                            push('X', fixed3(hw * -1 + e.x));
                        }
                    }
                } else {
                    if (s.y - hl <= hl) {
                        push('Y', fixed3(hl - s.y));
                        push('X', fixed3(hw));
                    }
                    if (e.y - hl <= hl) {
                        push('Y', fixed3(hl - e.y));
                        push('X', fixed3(hw) * -1);
                    }
                }
            } else if (flipped) {
                if (s.x <= width) {
                    push('X', fixed3(s.x * l.xFactor));
                    push('Y', fixed3(s.y * l.yFactor));
                }
                if (e.x <= width) {
                    push('X', fixed3(e.x * l.xFactor));
                    push('Y', fixed3(e.y * l.yFactor));
                }
            } else {
                if (s.y <= length) {
                    push('Y', fixed3(s.y * l.yFactor));
                    push('X', fixed3(s.x * l.xFactor));
                }
                if (e.y <= length) {
                    push('Y', fixed3(e.y * l.yFactor));
                    push('X', fixed3(e.x * l.xFactor));
                }
            }
            passes.emplace_back("");
            if ((flipped ? s.x >= width : s.y >= length) || !(so > 0) || pass >= kMaxPasses) {
                break;
            }
            start = flipped ? Pos{fixed3(e.x + so), s.y} : Pos{s.x, fixed3(e.y + so)};
            end = flipped ? Pos{fixed3(e.x + so * 2), e.y} : Pos{e.x, fixed3(e.y + so * 2)};
        }

        Lines code;
        if (!center) {
            append(code, perimeter(x, y, direction, std::nullopt, false));
            append(code, passes);
            append(code, returnToZero());
            return code;
        }
        append(code, {"(Entering Start Area)",
                      "G0 X" + num(fixed3(width / 2) * -1) + " Y" + num(fixed3(length / 2)),
                      "(End of Entering Start Area)"});
        append(code, ramp(direction));
        append(code, {"(Drawing Perimeter)", "G0 X" + num(fixed3((width / 2) * -1)), "G0 Y" + num(fixed3(length / 2)),
                      "G1 Y" + num(fixed3(length / 2) * -1), "G1 X" + num(fixed3(width / 2)),
                      "G1 Y" + num(fixed3(length / 2)), "G1 X" + num(fixed3(width / 2) * -1),
                      "(End of Drawing Perimeter)", ""});
        append(code, passes);
        append(code, returnToZero());
        return code;
    }

    const Options& s_;
    bool metric_;
};

using units::convertToImperial;
using units::convertToMetric;

}  // namespace

std::string_view patternName(Pattern pattern) {
    return pattern == Pattern::ZigZag ? "ZIG_ZAG_MOVEMENT" : "SPIRAL_MOVEMENT";
}

std::optional<Pattern> patternFromName(std::string_view name) {
    for (const Pattern pattern : {Pattern::Spiral, Pattern::ZigZag}) {
        if (patternName(pattern) == name) {
            return pattern;
        }
    }
    return std::nullopt;
}

std::string_view startPositionName(StartPosition position) {
    switch (position) {
        case StartPosition::BackLeft: return "START_POSITION_BACK_LEFT";
        case StartPosition::BackRight: return "START_POSITION_BACK_RIGHT";
        case StartPosition::FrontLeft: return "START_POSITION_FRONT_LEFT";
        case StartPosition::FrontRight: return "START_POSITION_FRONT_RIGHT";
        case StartPosition::Center: return "START_POSITION_CENTER";
    }
    return "START_POSITION_BACK_LEFT";
}

std::optional<StartPosition> startPositionFromName(std::string_view name) {
    for (const StartPosition position : {StartPosition::BackLeft, StartPosition::BackRight, StartPosition::FrontLeft,
                                         StartPosition::FrontRight, StartPosition::Center}) {
        if (startPositionName(position) == name) {
            return position;
        }
    }
    return std::nullopt;
}

std::vector<std::string> generateLines(const Options& options, bool metric) {
    return Generator(options, metric).generate();
}

std::string generate(const Options& options, bool metric) {
    const std::vector<std::string> lines = generateLines(options, metric);
    std::string text;
    for (std::size_t i = 0; i < lines.size(); ++i) {
        if (i != 0) {
            text += '\n';
        }
        text += lines[i];
    }
    return text;
}

Options toImperial(Options mm) {
    mm.bitDiameter = convertToImperial(mm.bitDiameter);
    mm.feedrate = convertToImperial(mm.feedrate);
    mm.length = convertToImperial(mm.length);
    mm.width = convertToImperial(mm.width);
    mm.skimDepth = convertToImperial(mm.skimDepth);
    mm.maxDepth = convertToImperial(mm.maxDepth);
    return mm;
}

Options toMetric(Options inches) {
    inches.bitDiameter = convertToMetric(inches.bitDiameter);
    inches.feedrate = convertToMetric(inches.feedrate);
    inches.length = convertToMetric(inches.length);
    inches.width = convertToMetric(inches.width);
    inches.skimDepth = convertToMetric(inches.skimDepth);
    inches.maxDepth = convertToMetric(inches.maxDepth);
    return inches;
}

}  // namespace gs::surfacing
