// The Surfacing tool against golden output from gSender's own generator
// (tests/data/surfacing_golden.json, written by tools/gen_surfacing_fixtures.mjs),
// plus the checks of upstream's surfacing-output.test.ts that still hold.

#include "gs/surfacing/surfacing.hpp"

#include <gtest/gtest.h>

#include <boost/json.hpp>

#include <algorithm>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace gs::surfacing;
namespace json = boost::json;

namespace {

const json::array& goldenCases() {
    static const json::value data = [] {
        std::ifstream in(GS_TEST_DATA_DIR "/surfacing_golden.json", std::ios::binary);
        std::stringstream text;
        text << in.rdbuf();
        return json::parse(text.str());
    }();
    return data.at("cases").as_array();
}

Options optionsFrom(const json::object& o) {
    Options s;
    s.bitDiameter = o.at("bitDiameter").to_number<double>();
    s.stepover = o.at("stepover").to_number<double>();
    s.feedrate = o.at("feedrate").to_number<double>();
    s.length = o.at("length").to_number<double>();
    s.width = o.at("width").to_number<double>();
    s.skimDepth = o.at("skimDepth").to_number<double>();
    s.maxDepth = o.at("maxDepth").to_number<double>();
    s.spindleRPM = o.at("spindleRPM").to_number<double>();
    s.type = *patternFromName(std::string(o.at("type").as_string()));
    s.startPosition = *startPositionFromName(std::string(o.at("startPosition").as_string()));
    s.spindle = std::string(o.at("spindle").as_string());
    s.cutDirectionFlipped = o.at("cutDirectionFlipped").as_bool();
    s.shouldDwell = o.at("shouldDwell").as_bool();
    s.flood = o.at("flood").as_bool();
    s.mist = o.at("mist").as_bool();
    s.toolNumber = static_cast<int>(o.at("toolNumber").to_number<double>());
    return s;
}

TEST(Surfacing, MatchesUpstreamForEveryGoldenCase) {
    const json::array& cases = goldenCases();
    ASSERT_GE(cases.size(), 40u);
    for (const json::value& value : cases) {
        const json::object& c = value.as_object();
        const std::string name(c.at("name").as_string());
        const std::vector<std::string> actual =
            generateLines(optionsFrom(c.at("surfacing").as_object()), c.at("units").as_string() == "mm");
        std::vector<std::string> expected;
        for (const json::value& line : c.at("lines").as_array()) {
            expected.emplace_back(line.as_string());
        }
        const auto [a, e] = std::mismatch(actual.begin(), actual.end(), expected.begin(), expected.end());
        if (a != actual.end() || e != expected.end()) {
            ADD_FAILURE() << name << " line " << (a - actual.begin()) << ":\n  actual:   "
                          << (a != actual.end() ? *a : "<end>") << "\n  expected: " << (e != expected.end() ? *e : "<end>");
        }
    }
}

TEST(Surfacing, UnitsSetTheProgramUnits) {
    EXPECT_NE(generate({}, true).find("G21 ;mm"), std::string::npos);
    EXPECT_NE(generate({}, false).find("G20 ;inches"), std::string::npos);
}

TEST(Surfacing, AToolNumberInsertsAToolChangeBeforeTheSpindleStarts) {
    const std::vector<std::string> none = generateLines({}, true);
    EXPECT_TRUE(std::none_of(none.begin(), none.end(), [](const std::string& l) { return l.starts_with("M6"); }));
    Options options;
    options.toolNumber = 3;
    const std::vector<std::string> lines = generateLines(options, true);
    const auto change = std::find(lines.begin(), lines.end(), "M6 T3");
    ASSERT_NE(change, lines.end());
    EXPECT_EQ(*(change + 1), "M3 S17000");
}

TEST(Surfacing, TheProgramTextJoinsTheLines) {
    const std::string text = generate({}, true);
    EXPECT_TRUE(text.starts_with("(Header)\n(Generated by gSender from Sienci Labs)\n"));
    EXPECT_TRUE(text.ends_with("M5 ;Turn off spindle\n(End of Footer)"));
    EXPECT_NE(text.find("(Header End)\n\n\n(*** Layer 1 ***)"), std::string::npos);  // "\n" spacer elements
}

TEST(Surfacing, DegenerateInputsStillFinish) {
    Options options;
    options.stepover = 0;  // upstream recurses until the stack overflows
    EXPECT_FALSE(generateLines(options, true).empty());
    options = {};
    options.skimDepth = 0;
    options.maxDepth = 2;
    EXPECT_FALSE(generateLines(options, true).empty());
    options = {};
    options.bitDiameter = 0;
    options.width = 0;
    options.length = 0;  // no ramp length: upstream loops forever
    EXPECT_FALSE(generateLines(options, true).empty());
}

TEST(Surfacing, InchWorkspacesSeeConvertedValues) {
    const Options inches = toImperial({});
    EXPECT_EQ(inches.bitDiameter, 0.866);
    EXPECT_EQ(inches.feedrate, 98.425);
    EXPECT_EQ(inches.width, 3.937);
    EXPECT_EQ(inches.stepover, 40);  // a percentage
    EXPECT_EQ(toMetric(inches).width, 100);
}

TEST(Surfacing, NamesRoundTrip) {
    EXPECT_EQ(patternFromName("ZIG_ZAG_MOVEMENT"), Pattern::ZigZag);
    EXPECT_EQ(startPositionFromName(startPositionName(StartPosition::Center)), StartPosition::Center);
    EXPECT_EQ(patternFromName("CIRCLE"), std::nullopt);
}

}  // namespace
