# Script mode worker for gs_embed_resources(). Writes a C++ source with one
# byte array per file plus a name -> bytes lookup table.
#   GS_OUT   output .cpp
#   GS_BASE  directory the resource names are relative to
#   GS_FILES '|' separated absolute file paths

string(REPLACE "|" ";" _files "${GS_FILES}")

set(_body "")
set(_entries "")
set(_index 0)
foreach(_file IN LISTS _files)
    file(READ "${_file}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _size "${_hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    # Keep source lines short; compilers cap logical line lengths.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n" _bytes "${_bytes}")
    file(RELATIVE_PATH _name "${GS_BASE}" "${_file}")
    string(APPEND _body "const unsigned char kData${_index}[] = {\n${_bytes}0x00};\n\n")
    string(APPEND _entries "    {\"${_name}\", kData${_index}, ${_size}},\n")
    math(EXPR _index "${_index} + 1")
endforeach()

set(_content "// Generated by GsEmbedScript.cmake - do not edit.
#include \"gs/core/resources.hpp\"

#include <cstddef>

namespace gs::resources {
namespace {

${_body}struct Entry {
    std::string_view name;
    const unsigned char* data;
    std::size_t size;
};

// The trailing sentinel keeps the array non-empty when nothing is embedded.
const Entry kEntries[] = {
${_entries}    {\"\", nullptr, 0},
};

}  // namespace

std::optional<std::string_view> find(std::string_view name) {
    for (const Entry& entry : kEntries) {
        if (entry.data != nullptr && entry.name == name) {
            return std::string_view(reinterpret_cast<const char*>(entry.data), entry.size);
        }
    }
    return std::nullopt;
}

std::vector<std::string_view> names() {
    std::vector<std::string_view> result;
    for (const Entry& entry : kEntries) {
        if (entry.data != nullptr) {
            result.push_back(entry.name);
        }
    }
    return result;
}

}  // namespace gs::resources
")

file(WRITE "${GS_OUT}.tmp" "${_content}")
file(COPY_FILE "${GS_OUT}.tmp" "${GS_OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${GS_OUT}.tmp")
