#include "gs/rotary/rotary.hpp"

#include "gs/core/resources.hpp"
#include "gs/util/jsnumber.hpp"
#include "gs/util/units.hpp"

#include <boost/json.hpp>

#include <cmath>
#include <numbers>

namespace gs::rotary {
namespace {

namespace json = boost::json;

std::string num(double value) {
    return js::numberToString(value);
}

std::string fixed(double value, int digits) {
    return js::toFixed(value, digits);
}

// Number(value.toFixed(digits)).
double round(double value, int digits) {
    return js::stringToNumber(js::toFixed(value, digits));
}

// SURFACING_DWELL_DURATION (s).
constexpr double kDwell = 4;

class StockTurning {
public:
    StockTurning(StockTurningOptions options, bool metric, bool rotaryMode)
        : o_(options), metric_(metric), rotaryMode_(rotaryMode) {
        // The heights are diameters; the program works in radii.
        o_.startHeight = round(options.startHeight / 2, 2);
        o_.finalHeight = round(options.finalHeight / 2, 2);
        // One pass (without rehoming) runs as two half spirals; more as full
        // spirals (whose count's parity is checked later).
        halfAndHalf_ = o_.startHeight - o_.stepdown <= o_.finalHeight && !o_.enableRehoming;
    }

    std::string generate() const {
        const std::string safeHeight = num(safeZ());
        std::vector<std::string> lines{
            "(Header)",
            "(Generated by gSender from Sienci Labs)",
            metric_ ? "G21 ;mm" : "G20 ;inches",
            "G1 F" + num(o_.feedrate),
            "G90",
        };
        if (o_.toolNumber != 0) {
            lines.push_back("M6 T" + std::to_string(o_.toolNumber));
        }
        lines.push_back("M3 S" + num(o_.spindleRPM));
        if (o_.shouldDwell) {
            lines.push_back("G04 P" + num(kDwell));
        }
        lines.push_back("(Header End)");
        lines.emplace_back("\n");

        // generateLayers(): from the start radius down by the stepdown.
        double depth = o_.startHeight;
        int count = 1;
        while (depth > o_.finalHeight) {
            lines.push_back("(*** Layer " + std::to_string(count) + " ***)");
            for (std::string& line : halfAndHalf_ ? halfAndHalfSpiral(depth) : fullSpiral(depth, count)) {
                lines.push_back(std::move(line));
            }
            lines.push_back("(*** End of Layer " + std::to_string(count) + " ***)");
            lines.emplace_back("\n");
            if (!(o_.stepdown > 0)) {
                break;  // upstream recurses forever
            }
            depth -= o_.stepdown;
            ++count;
        }

        // Back to zero (A only when not rehoming), then the footer.
        lines.emplace_back("G90");
        lines.push_back("G0 Z" + safeHeight);
        lines.push_back(o_.enableRehoming ? "G0 X0" : "G0 X0 A0");
        for (const char* line : {"\n", "(Footer)", "M5 ;Turn off spindle", "(End of Footer)"}) {
            lines.emplace_back(line);
        }

        std::string program;
        for (std::size_t i = 0; i < lines.size(); ++i) {
            if (i > 0) {
                program += '\n';
            }
            program += lines[i];
        }
        return program;
    }

private:
    double safeZ() const { return (metric_ ? 3 : 0.12) + o_.startHeight; }
    double defaultZ() const { return metric_ ? 25 : 0.98; }

    // processValue(): A values in inches when the workspace is both.
    double value(double v) const { return !metric_ && rotaryMode_ ? round(v / 25.4, 3) : v; }

    // The feed along the circumference at radius `z`.
    std::string plungeFeed(double z) const {
        return fixed((0.2 * 360 * o_.feedrate) / (z * 2 * std::numbers::pi), 3);
    }
    std::string spiralFeed(double z) const {
        return fixed((360 * o_.feedrate) / (z * 2 * std::numbers::pi), 3);
    }

    // The radius the spiral runs at, and whether this is the last stepdown.
    struct Depths {
        double current;
        double modified;
        bool finalStepdown;
    };
    Depths depths(double depth) const {
        Depths d{depth > 0 ? depth : defaultZ(), defaultZ(), false};
        if (depth > 0) {
            d.modified = depth - o_.stepdown > o_.finalHeight ? depth - o_.stepdown : o_.finalHeight;
        }
        d.finalStepdown = d.current - o_.stepdown <= o_.finalHeight;
        return d;
    }

    // Lines 5 and 14 of the half spirals: the last stepdown ramps down.
    std::string rampDown(double sign, const Depths& d) const {
        return d.finalStepdown ? "G1 A" + num(value(sign * 360)) + " Z" + fixed(-(d.current - o_.finalHeight), 3) +
                                     " F" + plungeFeed(d.current)
                               : std::string();
    }

    // The two halves: out along X with A turning one way, back the other.
    std::vector<std::string> halves(double depth, const Depths& d) const {
        const std::string safeHeight = num(safeZ());
        const std::string half = fixed(o_.stockLength / 2, 3);
        const std::string throttled = fixed(o_.feedrate * 0.2, 3);
        const double stepoverPercentage = o_.stepover / 100;
        return {
            "G91",
            rampDown(-1, d),
            "G1 A" + num(value(-360)),
            "G1 X" + half + " A" +
                fixed(value((0.5 * -360 * o_.stockLength) / (stepoverPercentage * o_.bitDiameter)), 3) + " F" +
                spiralFeed(d.modified),
            "G1 A" + num(value(-360)),
            "G90",
            "G0 Z" + safeHeight,
            "G0 X" + num(o_.stockLength) + " F" + throttled,
            "G0 Z" + num(depth) + " F" + throttled,
            "G91",
            rampDown(1, d),
            "G1 A" + num(value(360)),
            // -"50.000" is -50 in JavaScript.
            "G1 X" + num(-js::stringToNumber(half)) + " A" +
                fixed(value((0.5 * 360 * o_.stockLength) / (stepoverPercentage * o_.bitDiameter)), 3) + " F" +
                spiralFeed(d.modified),
            "G1 A" + num(value(360)),
        };
    }

    std::vector<std::string> halfAndHalfSpiral(double depth) const {
        const Depths d = depths(depth);
        std::vector<std::string> lines{"G0 Z" + num(safeZ()), "G0 X0 A0",
                                       "G0 Z" + num(depth) + " F" + fixed(o_.feedrate * 0.2, 3)};
        for (std::string& line : halves(depth, d)) {
            lines.push_back(std::move(line));
        }
        return lines;
    }

    std::vector<std::string> fullSpiral(double depth, int count) const {
        const Depths d = depths(depth);
        const double alternate = count % 2 == 0 ? 1 : -1;
        const double stepoverPercentage = o_.stepover / 100;
        // Math.ceil(...) % 2 === 0 (false for NaN and the infinities).
        const double stepdowns = std::ceil((o_.startHeight - o_.finalHeight) / o_.stepdown);
        const bool evenStepdowns = std::isfinite(stepdowns) && std::fmod(stepdowns, 2) == 0;
        const bool firstLayer = d.current == o_.startHeight;
        // -(x).toFixed(3): the number, without trailing zeros.
        const double zStep = -js::stringToNumber(fixed(d.finalStepdown ? d.current - o_.finalHeight : o_.stepdown, 3));
        std::vector<std::string> continuing{
            "G1 A" + num(value(alternate * 360)) + " Z" + num(zStep) + " F" + plungeFeed(d.current),
            "G1 A" + num(value(alternate * 360)),
            "G1 X" + num(-(alternate * o_.stockLength)) + " A" +
                fixed(value(alternate * ((360 * o_.stockLength) / (stepoverPercentage * o_.bitDiameter))), 3) +
                " F" + spiralFeed(d.modified),
            "G1 A" + num(value(alternate * 360)),
        };
        if (firstLayer) {
            std::vector<std::string> lines{"G0 Z" + num(safeZ()), "G0 X0 A0",
                                           "G0 Z" + num(depth) + " F" + fixed(o_.feedrate * 0.2, 3), "G91"};
            lines.insert(lines.end(), continuing.begin(), continuing.end());
            return lines;
        }
        if (!o_.enableRehoming && !evenStepdowns && d.finalStepdown) {
            return halves(depth, d);  // finalLayerBlock
        }
        return continuing;
    }

    StockTurningOptions o_;
    bool metric_;
    bool rotaryMode_;
    bool halfAndHalf_ = true;
};

std::string probeValue(double v, bool inches) {
    return num(inches ? round(v / 25.4, 3) : v);
}

// The toggle macro (ROTARY_TOGGLE_MACRO): settle, then move Y to where it
// is reported (in the new axis setup).
const std::vector<std::string>& toggleMacro() {
    static const std::vector<std::string> lines{"G04 P0.5", "G0 G90 Y[posy]"};
    return lines;
}

}  // namespace

StockTurningOptions toImperial(StockTurningOptions mm) {
    for (double* value : {&mm.stockLength, &mm.startHeight, &mm.finalHeight, &mm.stepdown, &mm.bitDiameter,
                          &mm.feedrate}) {
        *value = units::convertToImperial(*value);
    }
    return mm;
}

StockTurningOptions toMetric(StockTurningOptions inches) {
    for (double* value : {&inches.stockLength, &inches.startHeight, &inches.finalHeight, &inches.stepdown,
                          &inches.bitDiameter, &inches.feedrate}) {
        *value = units::convertToMetric(*value);
    }
    return inches;
}

std::string stockTurningProgram(const StockTurningOptions& options, bool metric, bool rotaryMode) {
    return StockTurning(options, metric, rotaryMode).generate();
}

std::vector<std::string> zAxisProbing(bool inches) {
    const auto v = [inches](double value) { return probeValue(value, inches); };
    return {
        "%PROBE_FAST_FEEDRATE = " + v(150),
        "%PROBE_SLOW_FEEDRATE = " + v(50),
        "%PROBE_RETRACTION = " + v(1),
        "%Z_AXIS_LARGE_MOVEMENT = " + v(39),
        "%Z_AXIS_LONG_MOVEMENT = " + v(30),
        "%Z_AXIS_SHORT_MOVEMENT = " + v(2),
        "G91 ; Relative positioning",
        inches ? "G20" : "G21",
        "G38.2 Z[-Z_AXIS_LONG_MOVEMENT] F[PROBE_FAST_FEEDRATE]",
        "G0 Z[PROBE_RETRACTION]",
        "G38.2 Z[-Z_AXIS_SHORT_MOVEMENT] F[PROBE_SLOW_FEEDRATE]",
        "G4 P0.15",
        "G10 L20 P0 Z[Z_AXIS_LARGE_MOVEMENT]",
        "G0 Z[Z_AXIS_SHORT_MOVEMENT]",
        "G90",
    };
}

std::vector<std::string> yAxisAlignmentProbing(bool inches) {
    const auto v = [inches](double value) { return probeValue(value, inches); };
    return {
        "%PROBE_FAST_FEEDRATE = " + v(150),
        "%PROBE_SLOW_FEEDRATE = " + v(50),
        "%PROBE_RETRACTION = " + v(1),
        "%CLEARANCE_HEIGHT = " + v(2),
        "%PROBE_HEIGHT = " + v(-3),
        "%Y_AXIS_LARGE_MOVEMENT = " + v(44),
        "%Y_AXIS_LONG_MOVEMENT = " + v(32),
        "%Y_AXIS_SHORT_MOVEMENT = " + v(2),
        "%Z_AXIS_LARGE_MOVEMENT = " + v(39),
        "%Z_AXIS_LONG_MOVEMENT = " + v(30),
        "%Z_AXIS_SHORT_MOVEMENT = " + v(2),
        "G91 ; Relative positioning",
        inches ? "G20" : "G21",
        "G38.2 Z[-Z_AXIS_LONG_MOVEMENT] F[PROBE_FAST_FEEDRATE]",
        "G4 P0.15",
        "G0 Z[CLEARANCE_HEIGHT]",
        "G0 Y[Y_AXIS_LONG_MOVEMENT]",
        "G0 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT]",
        "G38.2 Y[-Y_AXIS_LONG_MOVEMENT] F[PROBE_FAST_FEEDRATE]",
        "G0 Y[PROBE_RETRACTION]",
        "G38.2 Y[-Y_AXIS_SHORT_MOVEMENT] F[PROBE_SLOW_FEEDRATE]",
        "G4 P0.15",
        "%REAR_SEEK_POS = [posy]",
        "G0 Y[PROBE_RETRACTION]",
        "G0 Z[CLEARANCE_HEIGHT-PROBE_HEIGHT]",
        "G0 Y[-Y_AXIS_LARGE_MOVEMENT]",
        "G0 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT]",
        "G38.2 Y[Y_AXIS_LONG_MOVEMENT] F[PROBE_FAST_FEEDRATE]",
        "G0 Y[-PROBE_RETRACTION]",
        "G38.2 Y[Y_AXIS_SHORT_MOVEMENT] F[PROBE_SLOW_FEEDRATE]",
        "G4 P0.15",
        "%FRONT_SEEK_POS = [posy]",
        "G0 Y[-PROBE_RETRACTION]",
        "G0 Z[CLEARANCE_HEIGHT-PROBE_HEIGHT]",
        "%Y_SEEK_CENTERDIST = [REAR_SEEK_POS - FRONT_SEEK_POS]",
        "G0 Y[PROBE_RETRACTION+Y_SEEK_CENTERDIST/2]",
        "G10 L20 Y0",
        "G38.2 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT] F[PROBE_FAST_FEEDRATE]",
        "G0 Z[PROBE_RETRACTION]",
        "G38.2 Z[-Z_AXIS_SHORT_MOVEMENT] F[PROBE_SLOW_FEEDRATE]",
        "G4 P0.15",
        "G10 L20 Z[Z_AXIS_LARGE_MOVEMENT]",
        "G0 Z[CLEARANCE_HEIGHT]",
        "G90",
    };
}

const FirmwareValues& rotaryFirmwareSettings() {
    static const FirmwareValues values{{"$101", "19.75308642"}, {"$111", "8000.00"}, {"$20", "0"}, {"$21", "0"}};
    return values;
}

const FirmwareValues& defaultFirmwareSettings() {
    static const FirmwareValues values{{"$101", "200"}, {"$111", "4000"}, {"$20", "0"}, {"$21", "0"}};
    return values;
}

FirmwareValues currentFirmwareValues(const protocol::OrderedMap& settings) {
    FirmwareValues values;
    for (const char* key : {"$101", "$111", "$20", "$21"}) {
        values.emplace_back(key, settings.get(key));
    }
    return values;
}

std::vector<std::string> modeSwitchCommands(const ModeSwitch& change, const protocol::OrderedMap& settings) {
    std::vector<std::string> commands;
    if (!change.grblHal) {
        if (change.enable) {
            commands.emplace_back("G10 L20 P1 Y0");  // zero Y where it is
        }
        for (const auto& [key, value] : change.grblSettings) {
            commands.push_back(key + "=" + value);
        }
    } else {
        commands.emplace_back("G10 L20 P1 Y0");
        // A takes Y's settings and Y takes A's (both ways, the same swap).
        static constexpr std::pair<const char*, const char*> kPairs[] = {
            {"$103", "$101"}, {"$113", "$111"}, {"$123", "$121"}, {"$133", "$131"}};
        for (const auto& [a, y] : kPairs) {
            if (settings.has(y) && settings.has(a)) {
                commands.push_back(std::string(a) + "=" + settings.get(y));
            }
        }
        for (const auto& [a, y] : kPairs) {
            if (settings.has(y) && settings.has(a)) {
                commands.push_back(std::string(y) + "=" + settings.get(a));
            }
        }
    }
    commands.emplace_back("$$");
    for (const std::string& line : toggleMacro()) {
        commands.push_back(line);
    }
    return commands;
}

std::string mountingProgramName(const MountingSetup& setup) {
    const bool quarter = setup.quarterInchBit;
    if (!setup.linesUp) {
        return quarter ? "DOESNT_LINE_UP_QUARTER" : "DOESNT_LINE_UP_EIGHTH";  // a custom mounting: 2 holes
    }
    if (setup.holes != 10) {
        return quarter ? "QUARTER_INCH_SIX_HOLES" : "EIGHTH_INCH_SIX_HOLES";  // the standard 30" track
    }
    if (setup.longExtension) {
        return quarter ? "QUARTER_INCH_TEN_HOLES" : "EIGHTH_INCH_TEN_HOLES";  // with the 460 mm extension
    }
    return quarter ? "QUARTER_INCH_TEN_HOLES_SHORT" : "EIGHTH_INCH_TEN_HOLES_SHORT";
}

std::optional<std::string> mountingProgram(const MountingSetup& setup) {
    const std::optional<std::string_view> data = resources::find("data/rotary_mounting.json");
    if (!data) {
        return std::nullopt;
    }
    boost::system::error_code error;
    const json::value root = json::parse(*data, error);
    if (error || !root.is_object()) {
        return std::nullopt;
    }
    const json::value* holeTypes = root.as_object().if_contains("holeTypes");
    const json::value* program =
        holeTypes && holeTypes->is_object() ? holeTypes->as_object().if_contains(mountingProgramName(setup)) : nullptr;
    if (!program || !program->is_string()) {
        return std::nullopt;
    }
    return std::string(program->as_string());
}

}  // namespace gs::rotary
