// Writes the icons the QML UI uses into cppport/resources/icons as SVG files:
// react-icons components rendered as upstream renders them (react-dom/
// server), plus the SVG assets of gSender's own. Their colour stays
// `currentColor`; the UI's icon provider paints them in the colour asked for.
// Re-run after adding an icon to the list below.
//
//   node cppport/tools/extract_icons.mjs

import { createRequire } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const require = createRequire(join(repoRoot, 'package.json'));
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');

const out = resolve(here, '..', 'resources', 'icons');
// react-icons does not export its package.json; find it beside the entry.
const iconsVersion = JSON.parse(
    readFileSync(join(dirname(require.resolve('react-icons')), 'package.json'), 'utf8'),
).version;
mkdirSync(out, { recursive: true });

// [react-icons set, component] - where upstream uses them.
const icons = [
    // The navigation rail (features/navbar).
    ['io5', 'IoSpeedometerOutline'],
    ['ri', 'RiToolsFill'],
    ['fa', 'FaTasks'],
    // The top bar: connection, notifications, status icons.
    ['bs', 'BsUsbPlug'],
    ['bs', 'BsEthernet'],
    ['bs', 'BsCheckCircleFill'],
    ['pi', 'PiPlugLight'],
    ['gr', 'GrSatellite'],
    ['fa', 'FaArrowAltCircleRight'],
    ['lu', 'LuBell'],
    ['fa6', 'FaRegKeyboard'],
    ['lu', 'LuGamepad2'],
    // The machine status (MachineStatus, UnlockButton).
    ['fa', 'FaUnlock'],
    ['fa', 'FaHome'],
    ['fa', 'FaLock'],
    // The DRO: Go To, Park, Zero.
    ['fa6', 'FaPaperPlane'],
    ['ri', 'RiParkingFill'],
    ['vsc', 'VscTarget'],
    // File control, job control, the overrides.
    ['fa', 'FaFolderOpen'],
    ['md', 'MdKeyboardArrowDown'],
    ['md', 'MdKeyboardArrowLeft'],
    ['md', 'MdKeyboardArrowRight'],
    ['md', 'MdClose'],
    ['fa', 'FaRedo'],
    ['lia', 'LiaFileUploadSolid'],
    ['lu', 'LuFileCode2'],
    ['md', 'MdInfoOutline'],
    ['fi', 'FiClock'],
    ['lu', 'LuPencil'],
    ['lu', 'LuFootprints'],
    ['io5', 'IoPlayOutline'],
    ['pi', 'PiPause'],
    ['fi', 'FiOctagon'],
    ['tb', 'TbVector'],
    ['md', 'MdFormatListNumbered'],
    ['fa', 'FaPlay'],
    ['fa', 'FaUndo'],
    ['fa', 'FaMinus'],
    ['fa', 'FaPlus'],
    // The tool area (features/Tools): the tabs, the console (lucide, as
    // react-icons' lu set), probe, macros, spindle/laser, coolant, rotary.
    ['lu', 'LuCopy'],
    ['lu', 'LuEraser'],
    ['lu', 'LuExternalLink'],
    ['lu', 'LuUnplug'],
    ['lu', 'LuArrowDown'],
    ['lu', 'LuChevronRight'],
    ['lu', 'LuChevronLeft'],
    ['lu', 'LuChevronDown'],
    ['lu', 'LuChevronsLeft'],
    ['lu', 'LuChevronsRight'],
    ['lu', 'LuDot'],
    ['lu', 'LuCog'],
    ['lu', 'LuTriangleAlert'],
    ['lu', 'LuCircleAlert'],
    ['lu', 'LuOctagonAlert'],
    ['lu', 'LuPause'],
    ['lu', 'LuPlay'],
    ['lu', 'LuPlus'],
    ['lu', 'LuRotateCcw'],
    ['lu', 'LuEye'],
    ['lu', 'LuEyeOff'],
    ['lu', 'LuSearch'],
    ['lu', 'LuWrench'],
    ['lu', 'LuX'],
    ['lu', 'LuTrash'],
    ['fa', 'FaBan'],
    ['fa', 'FaCheck'],
    ['fa', 'FaEdit'],
    ['fa', 'FaEllipsisH'],
    ['fa', 'FaExclamation'],
    ['fa', 'FaFileExport'],
    ['fa', 'FaFileImport'],
    ['fa', 'FaLightbulb'],
    ['fa', 'FaRedoAlt'],
    ['fa', 'FaRegLightbulb'],
    ['fa', 'FaSatelliteDish'],
    ['fa', 'FaTimes'],
    ['fa', 'FaTrashAlt'],
    ['fa', 'FaUndoAlt'],
    ['fa', 'FaWater'],
    ['fa6', 'FaShower'],
];

for (const [set, name] of icons) {
    const component = require(`react-icons/${set}`)[name];
    if (!component) throw new Error(`react-icons/${set} has no ${name}`);
    // Sized by the viewBox rather than "1em", so a renderer draws it at its size.
    const svg = renderToStaticMarkup(React.createElement(component)).replace(/ (height|width)="1em"/g, '');
    writeFileSync(join(out, `${name}.svg`), `${svg}\n`, 'utf8');
}

// gSender's own: the navigation's Carve picture, the jog controls' labels.
const own = [
    ['src/app/src/features/navbar/assets/Carve.svg', 'Carve.svg'],
    ['src/app/src/features/Jogging/assets/labels.svg', 'JogWheelLabels.svg'],
    ['src/app/src/features/Jogging/assets/zLabels.svg', 'JogZLabels.svg'],
    ['src/app/src/features/Jogging/assets/aLabels.svg', 'JogALabels.svg'],
];
for (const [from, to] of own) {
    copyFileSync(join(repoRoot, from), join(out, to));
}

writeFileSync(
    join(out, 'README.md'),
    `# Icons

Generated by \`tools/extract_icons.mjs\` - do not edit. The icons come from
the icon sets react-icons ${iconsVersion} bundles, under their own
licences: Font Awesome Free (fa, fa6; CC BY 4.0), Lucide (lu; ISC), Ionicons
(io5; MIT), Remix Icon (ri; Apache 2.0), Bootstrap Icons (bs; MIT), Phosphor
(pi; MIT), Grommet (gr; Apache 2.0), VS Code Codicons (vsc; CC BY 4.0),
Material Design icons (md; Apache 2.0), Feather (fi; MIT), Line Awesome (lia;
MIT/CC BY 4.0), Tabler (tb; MIT).
Carve.svg and the Jog*Labels.svg files are gSender's own.
`,
    'utf8',
);
console.log(`wrote ${icons.length + own.length} icons to ${out}`);
